### ISSUE TITLE
DOKU

### ISSUE THREAD

**Issue by orhanoz** [Cagince/sudoku#1]
HANİ ONLİNE ODEME ? HANİ WHERE İS WEB SİTE ? ARKAPLAN RENGİNİ DEGİŞTİRDİN BİRAKTİN Mİ ? SUDOKU NE OLM :100:

**Comment by Cagince** [comment]
Algoritma alistirmasi yapiyorum olm :+1:  sizden haber yokki yaziyorum cevap yok bende kendimi sudokuya vurdum
